// Code generated by protoc-gen-go.
// source: godaiquest.proto
// DO NOT EDIT!

/*
Package godaiquest is a generated protocol buffer package.

It is generated from these files:
	godaiquest.proto

It has these top-level messages:
	AddUser
	Login
	GetDungeon
	DungeonInfo
	ImagePair
	ImagePairDic
	DungeonBlockImageInfo
	ObjectAttr
	ObjectAttrDic
	ObjectAttrInfo
	Tile
	TileDic
	TileInfo
	SetDungeon
	TilePaletteImageSet
	TilePalette
	SetBlockImagePalette
	AUser
	AUserDic
	UserInfo
	AItem
	AItemDic
	ItemInfo
	ALocation
	ALocationDic
	LocationInfo
	Signal
	SignalQueue
	IslandGround
	IslandGroundInfo
	AMessage
	AMessageDic
	MessageInfo
	APickuped
	PickupedInfo
	Ashiatolog
	ItemArticle
	ItemArticleDic
	ItemArticleInfo
	MonsterDic
	MonsterInfo
	RDReadItemDic
	RDReadItemInfo
	ARealMonster
	RealMonsterInfo
	ARealMonsterLocation
	RealMonsterLocationInfo
*/
package godaiquest

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AddUser struct {
	MailAddress      *string `protobuf:"bytes,1,opt,name=mail_address" json:"mail_address,omitempty"`
	UserName         *string `protobuf:"bytes,2,opt,name=user_name" json:"user_name,omitempty"`
	Password         *string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	UserFolder       *string `protobuf:"bytes,4,opt,name=user_folder" json:"user_folder,omitempty"`
	ComputerName     *string `protobuf:"bytes,5,opt,name=computer_name" json:"computer_name,omitempty"`
	UserImage        []byte  `protobuf:"bytes,6,opt,name=user_image" json:"user_image,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddUser) Reset()         { *m = AddUser{} }
func (m *AddUser) String() string { return proto.CompactTextString(m) }
func (*AddUser) ProtoMessage()    {}

func (m *AddUser) GetMailAddress() string {
	if m != nil && m.MailAddress != nil {
		return *m.MailAddress
	}
	return ""
}

func (m *AddUser) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *AddUser) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *AddUser) GetUserFolder() string {
	if m != nil && m.UserFolder != nil {
		return *m.UserFolder
	}
	return ""
}

func (m *AddUser) GetComputerName() string {
	if m != nil && m.ComputerName != nil {
		return *m.ComputerName
	}
	return ""
}

func (m *AddUser) GetUserImage() []byte {
	if m != nil {
		return m.UserImage
	}
	return nil
}

type Login struct {
	MailAddress      *string `protobuf:"bytes,1,opt,name=mail_address" json:"mail_address,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	ClientVersion    *uint32 `protobuf:"fixed32,3,opt,name=client_version" json:"client_version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}

func (m *Login) GetMailAddress() string {
	if m != nil && m.MailAddress != nil {
		return *m.MailAddress
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Login) GetClientVersion() uint32 {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return 0
}

type GetDungeon struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DungeonNumber    *int32 `protobuf:"varint,2,opt,name=dungeon_number" json:"dungeon_number,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetDungeon) Reset()         { *m = GetDungeon{} }
func (m *GetDungeon) String() string { return proto.CompactTextString(m) }
func (*GetDungeon) ProtoMessage()    {}

func (m *GetDungeon) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GetDungeon) GetDungeonNumber() int32 {
	if m != nil && m.DungeonNumber != nil {
		return *m.DungeonNumber
	}
	return 0
}

type DungeonInfo struct {
	Dungeon          []byte `protobuf:"bytes,1,opt,name=dungeon" json:"dungeon,omitempty"`
	SizeX            *int32 `protobuf:"varint,2,opt,name=size_x" json:"size_x,omitempty"`
	SizeY            *int32 `protobuf:"varint,3,opt,name=size_y" json:"size_y,omitempty"`
	DungeonNumber    *int32 `protobuf:"varint,4,opt,name=dungeon_number" json:"dungeon_number,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DungeonInfo) Reset()         { *m = DungeonInfo{} }
func (m *DungeonInfo) String() string { return proto.CompactTextString(m) }
func (*DungeonInfo) ProtoMessage()    {}

func (m *DungeonInfo) GetDungeon() []byte {
	if m != nil {
		return m.Dungeon
	}
	return nil
}

func (m *DungeonInfo) GetSizeX() int32 {
	if m != nil && m.SizeX != nil {
		return *m.SizeX
	}
	return 0
}

func (m *DungeonInfo) GetSizeY() int32 {
	if m != nil && m.SizeY != nil {
		return *m.SizeY
	}
	return 0
}

func (m *DungeonInfo) GetDungeonNumber() int32 {
	if m != nil && m.DungeonNumber != nil {
		return *m.DungeonNumber
	}
	return 0
}

type ImagePair struct {
	Number           *int32  `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Image            []byte  `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Owner            *int32  `protobuf:"varint,4,opt,name=owner" json:"owner,omitempty"`
	Created          *int64  `protobuf:"fixed64,5,opt,name=created" json:"created,omitempty"`
	CanItemImage     *bool   `protobuf:"varint,6,opt,name=can_item_image" json:"can_item_image,omitempty"`
	NewImage         *bool   `protobuf:"varint,7,opt,name=new_image" json:"new_image,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ImagePair) Reset()         { *m = ImagePair{} }
func (m *ImagePair) String() string { return proto.CompactTextString(m) }
func (*ImagePair) ProtoMessage()    {}

func (m *ImagePair) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *ImagePair) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ImagePair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ImagePair) GetOwner() int32 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *ImagePair) GetCreated() int64 {
	if m != nil && m.Created != nil {
		return *m.Created
	}
	return 0
}

func (m *ImagePair) GetCanItemImage() bool {
	if m != nil && m.CanItemImage != nil {
		return *m.CanItemImage
	}
	return false
}

func (m *ImagePair) GetNewImage() bool {
	if m != nil && m.NewImage != nil {
		return *m.NewImage
	}
	return false
}

type ImagePairDic struct {
	Index            *uint32    `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Imagepair        *ImagePair `protobuf:"bytes,2,opt,name=imagepair" json:"imagepair,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ImagePairDic) Reset()         { *m = ImagePairDic{} }
func (m *ImagePairDic) String() string { return proto.CompactTextString(m) }
func (*ImagePairDic) ProtoMessage()    {}

func (m *ImagePairDic) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ImagePairDic) GetImagepair() *ImagePair {
	if m != nil {
		return m.Imagepair
	}
	return nil
}

type DungeonBlockImageInfo struct {
	MaxImageNum      *uint32         `protobuf:"varint,1,opt,name=max_image_num" json:"max_image_num,omitempty"`
	ImageDic         []*ImagePairDic `protobuf:"bytes,2,rep,name=image_dic" json:"image_dic,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *DungeonBlockImageInfo) Reset()         { *m = DungeonBlockImageInfo{} }
func (m *DungeonBlockImageInfo) String() string { return proto.CompactTextString(m) }
func (*DungeonBlockImageInfo) ProtoMessage()    {}

func (m *DungeonBlockImageInfo) GetMaxImageNum() uint32 {
	if m != nil && m.MaxImageNum != nil {
		return *m.MaxImageNum
	}
	return 0
}

func (m *DungeonBlockImageInfo) GetImageDic() []*ImagePairDic {
	if m != nil {
		return m.ImageDic
	}
	return nil
}

type ObjectAttr struct {
	ObjectId         *int32 `protobuf:"varint,1,opt,name=object_id" json:"object_id,omitempty"`
	CanWalk          *bool  `protobuf:"varint,2,opt,name=can_walk" json:"can_walk,omitempty"`
	ItemId           *int32 `protobuf:"varint,3,opt,name=item_id" json:"item_id,omitempty"`
	BNew             *bool  `protobuf:"varint,4,opt,name=bNew" json:"bNew,omitempty"`
	Command          *int32 `protobuf:"varint,5,opt,name=command" json:"command,omitempty"`
	CommandSub       *int32 `protobuf:"varint,6,opt,name=command_sub" json:"command_sub,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ObjectAttr) Reset()         { *m = ObjectAttr{} }
func (m *ObjectAttr) String() string { return proto.CompactTextString(m) }
func (*ObjectAttr) ProtoMessage()    {}

func (m *ObjectAttr) GetObjectId() int32 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *ObjectAttr) GetCanWalk() bool {
	if m != nil && m.CanWalk != nil {
		return *m.CanWalk
	}
	return false
}

func (m *ObjectAttr) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *ObjectAttr) GetBNew() bool {
	if m != nil && m.BNew != nil {
		return *m.BNew
	}
	return false
}

func (m *ObjectAttr) GetCommand() int32 {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return 0
}

func (m *ObjectAttr) GetCommandSub() int32 {
	if m != nil && m.CommandSub != nil {
		return *m.CommandSub
	}
	return 0
}

type ObjectAttrDic struct {
	Index            *int32      `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	ObjectAttr       *ObjectAttr `protobuf:"bytes,2,opt,name=object_attr" json:"object_attr,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ObjectAttrDic) Reset()         { *m = ObjectAttrDic{} }
func (m *ObjectAttrDic) String() string { return proto.CompactTextString(m) }
func (*ObjectAttrDic) ProtoMessage()    {}

func (m *ObjectAttrDic) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ObjectAttrDic) GetObjectAttr() *ObjectAttr {
	if m != nil {
		return m.ObjectAttr
	}
	return nil
}

type ObjectAttrInfo struct {
	NewId            *int32           `protobuf:"varint,1,opt,name=new_id" json:"new_id,omitempty"`
	ObjectAttrDic    []*ObjectAttrDic `protobuf:"bytes,2,rep,name=object_attr_dic" json:"object_attr_dic,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ObjectAttrInfo) Reset()         { *m = ObjectAttrInfo{} }
func (m *ObjectAttrInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectAttrInfo) ProtoMessage()    {}

func (m *ObjectAttrInfo) GetNewId() int32 {
	if m != nil && m.NewId != nil {
		return *m.NewId
	}
	return 0
}

func (m *ObjectAttrInfo) GetObjectAttrDic() []*ObjectAttrDic {
	if m != nil {
		return m.ObjectAttrDic
	}
	return nil
}

type Tile struct {
	TileId           *uint64 `protobuf:"varint,1,opt,name=tile_id" json:"tile_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}

func (m *Tile) GetTileId() uint64 {
	if m != nil && m.TileId != nil {
		return *m.TileId
	}
	return 0
}

type TileDic struct {
	Index            *uint64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Tile             *Tile   `protobuf:"bytes,2,opt,name=tile" json:"tile,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TileDic) Reset()         { *m = TileDic{} }
func (m *TileDic) String() string { return proto.CompactTextString(m) }
func (*TileDic) ProtoMessage()    {}

func (m *TileDic) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *TileDic) GetTile() *Tile {
	if m != nil {
		return m.Tile
	}
	return nil
}

type TileInfo struct {
	TileDic          []*TileDic `protobuf:"bytes,1,rep,name=tile_dic" json:"tile_dic,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *TileInfo) Reset()         { *m = TileInfo{} }
func (m *TileInfo) String() string { return proto.CompactTextString(m) }
func (*TileInfo) ProtoMessage()    {}

func (m *TileInfo) GetTileDic() []*TileDic {
	if m != nil {
		return m.TileDic
	}
	return nil
}

type SetDungeon struct {
	UserId           *int32                 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	DungeonNumber    *int32                 `protobuf:"varint,2,opt,name=dungeon_number" json:"dungeon_number,omitempty"`
	DungeonInfo      *DungeonInfo           `protobuf:"bytes,3,opt,name=dungeon_info" json:"dungeon_info,omitempty"`
	Images           *DungeonBlockImageInfo `protobuf:"bytes,4,opt,name=images" json:"images,omitempty"`
	ObjectInfo       *ObjectAttrInfo        `protobuf:"bytes,5,opt,name=object_info" json:"object_info,omitempty"`
	TileInfo         *TileInfo              `protobuf:"bytes,6,opt,name=tile_info" json:"tile_info,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *SetDungeon) Reset()         { *m = SetDungeon{} }
func (m *SetDungeon) String() string { return proto.CompactTextString(m) }
func (*SetDungeon) ProtoMessage()    {}

func (m *SetDungeon) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *SetDungeon) GetDungeonNumber() int32 {
	if m != nil && m.DungeonNumber != nil {
		return *m.DungeonNumber
	}
	return 0
}

func (m *SetDungeon) GetDungeonInfo() *DungeonInfo {
	if m != nil {
		return m.DungeonInfo
	}
	return nil
}

func (m *SetDungeon) GetImages() *DungeonBlockImageInfo {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *SetDungeon) GetObjectInfo() *ObjectAttrInfo {
	if m != nil {
		return m.ObjectInfo
	}
	return nil
}

func (m *SetDungeon) GetTileInfo() *TileInfo {
	if m != nil {
		return m.TileInfo
	}
	return nil
}

type TilePaletteImageSet struct {
	TileId           *uint64 `protobuf:"varint,1,opt,name=tile_id" json:"tile_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TilePaletteImageSet) Reset()         { *m = TilePaletteImageSet{} }
func (m *TilePaletteImageSet) String() string { return proto.CompactTextString(m) }
func (*TilePaletteImageSet) ProtoMessage()    {}

func (m *TilePaletteImageSet) GetTileId() uint64 {
	if m != nil && m.TileId != nil {
		return *m.TileId
	}
	return 0
}

type TilePalette struct {
	UserId           *int32                 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	ImageSet         []*TilePaletteImageSet `protobuf:"bytes,2,rep,name=image_set" json:"image_set,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *TilePalette) Reset()         { *m = TilePalette{} }
func (m *TilePalette) String() string { return proto.CompactTextString(m) }
func (*TilePalette) ProtoMessage()    {}

func (m *TilePalette) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *TilePalette) GetImageSet() []*TilePaletteImageSet {
	if m != nil {
		return m.ImageSet
	}
	return nil
}

type SetBlockImagePalette struct {
	UserId           *int32       `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	TilePalette      *TilePalette `protobuf:"bytes,2,opt,name=tile_palette" json:"tile_palette,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SetBlockImagePalette) Reset()         { *m = SetBlockImagePalette{} }
func (m *SetBlockImagePalette) String() string { return proto.CompactTextString(m) }
func (*SetBlockImagePalette) ProtoMessage()    {}

func (m *SetBlockImagePalette) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *SetBlockImagePalette) GetTilePalette() *TilePalette {
	if m != nil {
		return m.TilePalette
	}
	return nil
}

type AUser struct {
	UserId           *int32  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	MailAddress      *string `protobuf:"bytes,2,opt,name=mail_address" json:"mail_address,omitempty"`
	UserName         *string `protobuf:"bytes,3,opt,name=user_name" json:"user_name,omitempty"`
	UserImage        []byte  `protobuf:"bytes,4,opt,name=user_image" json:"user_image,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AUser) Reset()         { *m = AUser{} }
func (m *AUser) String() string { return proto.CompactTextString(m) }
func (*AUser) ProtoMessage()    {}

func (m *AUser) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *AUser) GetMailAddress() string {
	if m != nil && m.MailAddress != nil {
		return *m.MailAddress
	}
	return ""
}

func (m *AUser) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *AUser) GetUserImage() []byte {
	if m != nil {
		return m.UserImage
	}
	return nil
}

type AUserDic struct {
	Index            *int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Auser            *AUser `protobuf:"bytes,2,opt,name=auser" json:"auser,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AUserDic) Reset()         { *m = AUserDic{} }
func (m *AUserDic) String() string { return proto.CompactTextString(m) }
func (*AUserDic) ProtoMessage()    {}

func (m *AUserDic) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *AUserDic) GetAuser() *AUser {
	if m != nil {
		return m.Auser
	}
	return nil
}

type UserInfo struct {
	UesrDic          []*AUserDic `protobuf:"bytes,1,rep,name=uesr_dic" json:"uesr_dic,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}

func (m *UserInfo) GetUesrDic() []*AUserDic {
	if m != nil {
		return m.UesrDic
	}
	return nil
}

type AItem struct {
	ItemId           *int32  `protobuf:"varint,1,opt,name=item_id" json:"item_id,omitempty"`
	ItemImageId      *int32  `protobuf:"varint,2,opt,name=item_image_id" json:"item_image_id,omitempty"`
	HeaderString     *string `protobuf:"bytes,3,opt,name=header_string" json:"header_string,omitempty"`
	HeaderImage      []byte  `protobuf:"bytes,4,opt,name=header_image" json:"header_image,omitempty"`
	BNew             *bool   `protobuf:"varint,5,opt,name=bNew" json:"bNew,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AItem) Reset()         { *m = AItem{} }
func (m *AItem) String() string { return proto.CompactTextString(m) }
func (*AItem) ProtoMessage()    {}

func (m *AItem) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *AItem) GetItemImageId() int32 {
	if m != nil && m.ItemImageId != nil {
		return *m.ItemImageId
	}
	return 0
}

func (m *AItem) GetHeaderString() string {
	if m != nil && m.HeaderString != nil {
		return *m.HeaderString
	}
	return ""
}

func (m *AItem) GetHeaderImage() []byte {
	if m != nil {
		return m.HeaderImage
	}
	return nil
}

func (m *AItem) GetBNew() bool {
	if m != nil && m.BNew != nil {
		return *m.BNew
	}
	return false
}

type AItemDic struct {
	Index            *int32 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Aitem            *AItem `protobuf:"bytes,2,opt,name=aitem" json:"aitem,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AItemDic) Reset()         { *m = AItemDic{} }
func (m *AItemDic) String() string { return proto.CompactTextString(m) }
func (*AItemDic) ProtoMessage()    {}

func (m *AItemDic) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *AItemDic) GetAitem() *AItem {
	if m != nil {
		return m.Aitem
	}
	return nil
}

type ItemInfo struct {
	AitemDic         []*AItemDic `protobuf:"bytes,1,rep,name=aitem_dic" json:"aitem_dic,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ItemInfo) Reset()         { *m = ItemInfo{} }
func (m *ItemInfo) String() string { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()    {}

func (m *ItemInfo) GetAitemDic() []*AItemDic {
	if m != nil {
		return m.AitemDic
	}
	return nil
}

type ALocation struct {
	UserId           *int32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Ix               *int32 `protobuf:"varint,2,opt,name=ix" json:"ix,omitempty"`
	Iy               *int32 `protobuf:"varint,3,opt,name=iy" json:"iy,omitempty"`
	DungeonUserId    *int32 `protobuf:"varint,4,opt,name=dungeon_user_id" json:"dungeon_user_id,omitempty"`
	DungeonNumber    *int32 `protobuf:"varint,5,opt,name=dungeon_number" json:"dungeon_number,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ALocation) Reset()         { *m = ALocation{} }
func (m *ALocation) String() string { return proto.CompactTextString(m) }
func (*ALocation) ProtoMessage()    {}

func (m *ALocation) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ALocation) GetIx() int32 {
	if m != nil && m.Ix != nil {
		return *m.Ix
	}
	return 0
}

func (m *ALocation) GetIy() int32 {
	if m != nil && m.Iy != nil {
		return *m.Iy
	}
	return 0
}

func (m *ALocation) GetDungeonUserId() int32 {
	if m != nil && m.DungeonUserId != nil {
		return *m.DungeonUserId
	}
	return 0
}

func (m *ALocation) GetDungeonNumber() int32 {
	if m != nil && m.DungeonNumber != nil {
		return *m.DungeonNumber
	}
	return 0
}

type ALocationDic struct {
	Index            *int32     `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Alocation        *ALocation `protobuf:"bytes,2,opt,name=alocation" json:"alocation,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ALocationDic) Reset()         { *m = ALocationDic{} }
func (m *ALocationDic) String() string { return proto.CompactTextString(m) }
func (*ALocationDic) ProtoMessage()    {}

func (m *ALocationDic) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ALocationDic) GetAlocation() *ALocation {
	if m != nil {
		return m.Alocation
	}
	return nil
}

type LocationInfo struct {
	AlocationDic     []*ALocationDic `protobuf:"bytes,1,rep,name=alocation_dic" json:"alocation_dic,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *LocationInfo) Reset()         { *m = LocationInfo{} }
func (m *LocationInfo) String() string { return proto.CompactTextString(m) }
func (*LocationInfo) ProtoMessage()    {}

func (m *LocationInfo) GetAlocationDic() []*ALocationDic {
	if m != nil {
		return m.AlocationDic
	}
	return nil
}

type Signal struct {
	Signal           *int32 `protobuf:"varint,1,opt,name=signal" json:"signal,omitempty"`
	Id               *int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Ix               *int32 `protobuf:"varint,3,opt,name=ix" json:"ix,omitempty"`
	Iy               *int32 `protobuf:"varint,4,opt,name=iy" json:"iy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}

func (m *Signal) GetSignal() int32 {
	if m != nil && m.Signal != nil {
		return *m.Signal
	}
	return 0
}

func (m *Signal) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Signal) GetIx() int32 {
	if m != nil && m.Ix != nil {
		return *m.Ix
	}
	return 0
}

func (m *Signal) GetIy() int32 {
	if m != nil && m.Iy != nil {
		return *m.Iy
	}
	return 0
}

type SignalQueue struct {
	SystemMessage    *string   `protobuf:"bytes,1,opt,name=system_message" json:"system_message,omitempty"`
	Signals          []*Signal `protobuf:"bytes,2,rep,name=signals" json:"signals,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *SignalQueue) Reset()         { *m = SignalQueue{} }
func (m *SignalQueue) String() string { return proto.CompactTextString(m) }
func (*SignalQueue) ProtoMessage()    {}

func (m *SignalQueue) GetSystemMessage() string {
	if m != nil && m.SystemMessage != nil {
		return *m.SystemMessage
	}
	return ""
}

func (m *SignalQueue) GetSignals() []*Signal {
	if m != nil {
		return m.Signals
	}
	return nil
}

type IslandGround struct {
	UserId           *int32 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Ix1              *int32 `protobuf:"varint,2,opt,name=ix1" json:"ix1,omitempty"`
	Iy1              *int32 `protobuf:"varint,3,opt,name=iy1" json:"iy1,omitempty"`
	Ix2              *int32 `protobuf:"varint,4,opt,name=ix2" json:"ix2,omitempty"`
	Iy2              *int32 `protobuf:"varint,5,opt,name=iy2" json:"iy2,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IslandGround) Reset()         { *m = IslandGround{} }
func (m *IslandGround) String() string { return proto.CompactTextString(m) }
func (*IslandGround) ProtoMessage()    {}

func (m *IslandGround) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *IslandGround) GetIx1() int32 {
	if m != nil && m.Ix1 != nil {
		return *m.Ix1
	}
	return 0
}

func (m *IslandGround) GetIy1() int32 {
	if m != nil && m.Iy1 != nil {
		return *m.Iy1
	}
	return 0
}

func (m *IslandGround) GetIx2() int32 {
	if m != nil && m.Ix2 != nil {
		return *m.Ix2
	}
	return 0
}

func (m *IslandGround) GetIy2() int32 {
	if m != nil && m.Iy2 != nil {
		return *m.Iy2
	}
	return 0
}

type IslandGroundInfo struct {
	GroundList       []*IslandGround `protobuf:"bytes,1,rep,name=ground_list" json:"ground_list,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *IslandGroundInfo) Reset()         { *m = IslandGroundInfo{} }
func (m *IslandGroundInfo) String() string { return proto.CompactTextString(m) }
func (*IslandGroundInfo) ProtoMessage()    {}

func (m *IslandGroundInfo) GetGroundList() []*IslandGround {
	if m != nil {
		return m.GroundList
	}
	return nil
}

type AMessage struct {
	UesrId           *int32  `protobuf:"varint,1,opt,name=uesr_id" json:"uesr_id,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AMessage) Reset()         { *m = AMessage{} }
func (m *AMessage) String() string { return proto.CompactTextString(m) }
func (*AMessage) ProtoMessage()    {}

func (m *AMessage) GetUesrId() int32 {
	if m != nil && m.UesrId != nil {
		return *m.UesrId
	}
	return 0
}

func (m *AMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type AMessageDic struct {
	Index            *int32    `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Amessage         *AMessage `protobuf:"bytes,2,opt,name=amessage" json:"amessage,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *AMessageDic) Reset()         { *m = AMessageDic{} }
func (m *AMessageDic) String() string { return proto.CompactTextString(m) }
func (*AMessageDic) ProtoMessage()    {}

func (m *AMessageDic) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *AMessageDic) GetAmessage() *AMessage {
	if m != nil {
		return m.Amessage
	}
	return nil
}

type MessageInfo struct {
	MessageDic       []*AMessageDic `protobuf:"bytes,1,rep,name=message_dic" json:"message_dic,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}

func (m *MessageInfo) GetMessageDic() []*AMessageDic {
	if m != nil {
		return m.MessageDic
	}
	return nil
}

type APickuped struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=item_id" json:"item_id,omitempty"`
	UserId           *int32 `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	DateTime         *int64 `protobuf:"fixed64,3,opt,name=date_time" json:"date_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *APickuped) Reset()         { *m = APickuped{} }
func (m *APickuped) String() string { return proto.CompactTextString(m) }
func (*APickuped) ProtoMessage()    {}

func (m *APickuped) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *APickuped) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *APickuped) GetDateTime() int64 {
	if m != nil && m.DateTime != nil {
		return *m.DateTime
	}
	return 0
}

type PickupedInfo struct {
	Apickuped        []*APickuped `protobuf:"bytes,1,rep,name=apickuped" json:"apickuped,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PickupedInfo) Reset()         { *m = PickupedInfo{} }
func (m *PickupedInfo) String() string { return proto.CompactTextString(m) }
func (*PickupedInfo) ProtoMessage()    {}

func (m *PickupedInfo) GetApickuped() []*APickuped {
	if m != nil {
		return m.Apickuped
	}
	return nil
}

type Ashiatolog struct {
	Alog             []string `protobuf:"bytes,1,rep,name=alog" json:"alog,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Ashiatolog) Reset()         { *m = Ashiatolog{} }
func (m *Ashiatolog) String() string { return proto.CompactTextString(m) }
func (*Ashiatolog) ProtoMessage()    {}

func (m *Ashiatolog) GetAlog() []string {
	if m != nil {
		return m.Alog
	}
	return nil
}

type ItemArticle struct {
	ItemId           *int32  `protobuf:"varint,1,opt,name=item_id" json:"item_id,omitempty"`
	ArticleId        *int32  `protobuf:"varint,2,opt,name=article_id" json:"article_id,omitempty"`
	UserId           *int32  `protobuf:"varint,3,opt,name=user_id" json:"user_id,omitempty"`
	Contents         *string `protobuf:"bytes,4,opt,name=contents" json:"contents,omitempty"`
	CretaeTime       *int64  `protobuf:"fixed64,5,opt,name=cretae_time" json:"cretae_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ItemArticle) Reset()         { *m = ItemArticle{} }
func (m *ItemArticle) String() string { return proto.CompactTextString(m) }
func (*ItemArticle) ProtoMessage()    {}

func (m *ItemArticle) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *ItemArticle) GetArticleId() int32 {
	if m != nil && m.ArticleId != nil {
		return *m.ArticleId
	}
	return 0
}

func (m *ItemArticle) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ItemArticle) GetContents() string {
	if m != nil && m.Contents != nil {
		return *m.Contents
	}
	return ""
}

func (m *ItemArticle) GetCretaeTime() int64 {
	if m != nil && m.CretaeTime != nil {
		return *m.CretaeTime
	}
	return 0
}

type ItemArticleDic struct {
	Index            *int32       `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	ItemArticle      *ItemArticle `protobuf:"bytes,2,opt,name=item_article" json:"item_article,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ItemArticleDic) Reset()         { *m = ItemArticleDic{} }
func (m *ItemArticleDic) String() string { return proto.CompactTextString(m) }
func (*ItemArticleDic) ProtoMessage()    {}

func (m *ItemArticleDic) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *ItemArticleDic) GetItemArticle() *ItemArticle {
	if m != nil {
		return m.ItemArticle
	}
	return nil
}

type ItemArticleInfo struct {
	ItemId           *int32            `protobuf:"varint,1,opt,name=item_id" json:"item_id,omitempty"`
	ItemArticleDic   []*ItemArticleDic `protobuf:"bytes,2,rep,name=item_article_dic" json:"item_article_dic,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ItemArticleInfo) Reset()         { *m = ItemArticleInfo{} }
func (m *ItemArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ItemArticleInfo) ProtoMessage()    {}

func (m *ItemArticleInfo) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *ItemArticleInfo) GetItemArticleDic() []*ItemArticleDic {
	if m != nil {
		return m.ItemArticleDic
	}
	return nil
}

type MonsterDic struct {
	Key              *int32 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MonsterDic) Reset()         { *m = MonsterDic{} }
func (m *MonsterDic) String() string { return proto.CompactTextString(m) }
func (*MonsterDic) ProtoMessage()    {}

func (m *MonsterDic) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *MonsterDic) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type MonsterInfo struct {
	MonsterDic       []*MonsterDic `protobuf:"bytes,1,rep,name=monster_dic" json:"monster_dic,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *MonsterInfo) Reset()         { *m = MonsterInfo{} }
func (m *MonsterInfo) String() string { return proto.CompactTextString(m) }
func (*MonsterInfo) ProtoMessage()    {}

func (m *MonsterInfo) GetMonsterDic() []*MonsterDic {
	if m != nil {
		return m.MonsterDic
	}
	return nil
}

type RDReadItemDic struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=item_id" json:"item_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RDReadItemDic) Reset()         { *m = RDReadItemDic{} }
func (m *RDReadItemDic) String() string { return proto.CompactTextString(m) }
func (*RDReadItemDic) ProtoMessage()    {}

func (m *RDReadItemDic) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

type RDReadItemInfo struct {
	UserId           *int32           `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	ReadItemDic      []*RDReadItemDic `protobuf:"bytes,2,rep,name=read_item_dic" json:"read_item_dic,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RDReadItemInfo) Reset()         { *m = RDReadItemInfo{} }
func (m *RDReadItemInfo) String() string { return proto.CompactTextString(m) }
func (*RDReadItemInfo) ProtoMessage()    {}

func (m *RDReadItemInfo) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *RDReadItemInfo) GetReadItemDic() []*RDReadItemDic {
	if m != nil {
		return m.ReadItemDic
	}
	return nil
}

type ARealMonster struct {
	MonsterId        *int32  `protobuf:"varint,1,opt,name=monster_id" json:"monster_id,omitempty"`
	MonsterName      *string `protobuf:"bytes,2,opt,name=monster_name" json:"monster_name,omitempty"`
	MonsterImage     []byte  `protobuf:"bytes,3,opt,name=monster_image" json:"monster_image,omitempty"`
	MonsterExpvalue  *int32  `protobuf:"varint,4,opt,name=monster_expvalue" json:"monster_expvalue,omitempty"`
	MonsterSpell     *string `protobuf:"bytes,5,opt,name=monster_spell" json:"monster_spell,omitempty"`
	MonsterSrcId     *int32  `protobuf:"varint,6,opt,name=monster_src_id" json:"monster_src_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ARealMonster) Reset()         { *m = ARealMonster{} }
func (m *ARealMonster) String() string { return proto.CompactTextString(m) }
func (*ARealMonster) ProtoMessage()    {}

func (m *ARealMonster) GetMonsterId() int32 {
	if m != nil && m.MonsterId != nil {
		return *m.MonsterId
	}
	return 0
}

func (m *ARealMonster) GetMonsterName() string {
	if m != nil && m.MonsterName != nil {
		return *m.MonsterName
	}
	return ""
}

func (m *ARealMonster) GetMonsterImage() []byte {
	if m != nil {
		return m.MonsterImage
	}
	return nil
}

func (m *ARealMonster) GetMonsterExpvalue() int32 {
	if m != nil && m.MonsterExpvalue != nil {
		return *m.MonsterExpvalue
	}
	return 0
}

func (m *ARealMonster) GetMonsterSpell() string {
	if m != nil && m.MonsterSpell != nil {
		return *m.MonsterSpell
	}
	return ""
}

func (m *ARealMonster) GetMonsterSrcId() int32 {
	if m != nil && m.MonsterSrcId != nil {
		return *m.MonsterSrcId
	}
	return 0
}

type RealMonsterInfo struct {
	RealMonster      []*ARealMonster `protobuf:"bytes,1,rep,name=real_monster" json:"real_monster,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RealMonsterInfo) Reset()         { *m = RealMonsterInfo{} }
func (m *RealMonsterInfo) String() string { return proto.CompactTextString(m) }
func (*RealMonsterInfo) ProtoMessage()    {}

func (m *RealMonsterInfo) GetRealMonster() []*ARealMonster {
	if m != nil {
		return m.RealMonster
	}
	return nil
}

type ARealMonsterLocation struct {
	MonsterId        *int32 `protobuf:"varint,1,opt,name=monster_id" json:"monster_id,omitempty"`
	MonsterIx        *int32 `protobuf:"varint,2,opt,name=monster_ix" json:"monster_ix,omitempty"`
	MonsterIy        *int32 `protobuf:"varint,3,opt,name=monster_iy" json:"monster_iy,omitempty"`
	DungeonNumber    *int32 `protobuf:"varint,4,opt,name=dungeon_number" json:"dungeon_number,omitempty"`
	MonsterSrcId     *int32 `protobuf:"varint,5,opt,name=monster_src_id" json:"monster_src_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ARealMonsterLocation) Reset()         { *m = ARealMonsterLocation{} }
func (m *ARealMonsterLocation) String() string { return proto.CompactTextString(m) }
func (*ARealMonsterLocation) ProtoMessage()    {}

func (m *ARealMonsterLocation) GetMonsterId() int32 {
	if m != nil && m.MonsterId != nil {
		return *m.MonsterId
	}
	return 0
}

func (m *ARealMonsterLocation) GetMonsterIx() int32 {
	if m != nil && m.MonsterIx != nil {
		return *m.MonsterIx
	}
	return 0
}

func (m *ARealMonsterLocation) GetMonsterIy() int32 {
	if m != nil && m.MonsterIy != nil {
		return *m.MonsterIy
	}
	return 0
}

func (m *ARealMonsterLocation) GetDungeonNumber() int32 {
	if m != nil && m.DungeonNumber != nil {
		return *m.DungeonNumber
	}
	return 0
}

func (m *ARealMonsterLocation) GetMonsterSrcId() int32 {
	if m != nil && m.MonsterSrcId != nil {
		return *m.MonsterSrcId
	}
	return 0
}

type RealMonsterLocationInfo struct {
	LocationList     []*ARealMonsterLocation `protobuf:"bytes,1,rep,name=location_list" json:"location_list,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RealMonsterLocationInfo) Reset()         { *m = RealMonsterLocationInfo{} }
func (m *RealMonsterLocationInfo) String() string { return proto.CompactTextString(m) }
func (*RealMonsterLocationInfo) ProtoMessage()    {}

func (m *RealMonsterLocationInfo) GetLocationList() []*ARealMonsterLocation {
	if m != nil {
		return m.LocationList
	}
	return nil
}

func init() {
}
